COMPREHENSION_TOPICS = {
    "A1": [
        "la famille",
        "l'école",
        "les amis",
        "les repas",
        "les loisirs",
        "la maison",
        "la routine quotidienne",
        "les vêtements",
        "les animaux",
        "le week-end",
        "le matin",
        "les courses",
        "le téléphone",
        "les vacances simples",
        "les saisons"
    ],

    "A2": [
        "les vacances",
        "une fête",
        "la ville",
        "les transports",
        "les habitudes",
        "un souvenir d'enfance",
        "une journée spéciale",
        "les relations amicales",
        "le sport",
        "la nourriture",
        "les sorties",
        "le shopping",
        "la météo",
        "les études",
        "les activités du week-end"
    ],

    "B1": [
        "les réseaux sociaux",
        "le sport",
        "l'éducation",
        "les voyages",
        "la santé",
        "le travail",
        "les amis",
        "la technologie",
        "la musique",
        "les films",
        "la famille moderne",
        "les habitudes de vie",
        "le stress",
        "les loisirs",
        "la communication"
    ],

    "B2": [
        "le changement climatique",
        "le télétravail",
        "les médias",
        "la technologie",
        "la consommation",
        "la mondialisation",
        "les inégalités sociales",
        "l'éducation moderne",
        "la santé mentale",
        "le travail et la vie personnelle",
        "les influenceurs",
        "la publicité",
        "la culture",
        "les langues",
        "le développement durable"
    ],

    "C1": [
        "la culture",
        "l'identité",
        "les inégalités",
        "la liberté",
        "l'État",
        "la société moderne",
        "le pouvoir",
        "les médias",
        "l'éthique",
        "l'éducation",
        "la justice sociale",
        "la mondialisation culturelle",
        "le progrès",
        "les relations humaines",
        "la pensée critique"
    ],

    "C2": [
        "la vérité",
        "le progrès",
        "la conscience",
        "la démocratie",
        "le pouvoir",
        "la moralité",
        "le langage",
        "la perception de la réalité",
        "le temps",
        "la mémoire",
        "le libre arbitre",
        "la condition humaine",
        "la justice",
        "la philosophie moderne",
        "l'avenir de l'humanité"
    ]
}