const TIPS = [
  {c:"Pronunciation",t:"The letter H is always silent in French. 'L'heure' sounds like 'lure'."},
  {c:"Pronunciation",t:"French R is made at the back of the throat — like gargling gently."},
  {c:"Pronunciation",t:"Nasal vowels (an, en, in, on, un) are pronounced through the nose without closing it."},
  {c:"Pronunciation",t:"The -ent verb ending for third-person plural is always silent: ils parlent = 'il parl'."},
  {c:"Pronunciation",t:"'U' in French has no English equivalent — round your lips as if to say 'oo' then say 'ee'."},
  {c:"Pronunciation",t:"Liaison: when a word ending in a consonant precedes a vowel, you link them: 'les amis' = 'lay-za-mee'."},
  {c:"Pronunciation",t:"Final consonants are usually silent. Exception: C, R, F, L are often pronounced (think: CaReFuL)."},
  {c:"Pronunciation",t:"'Eu' and 'oeu' sound like the English word 'her' but shorter."},
  {c:"Pronunciation",t:"The word 'plus' has three different pronunciations depending on context."},
  {c:"Pronunciation",t:"French doesn't stress syllables the way English does — every syllable has roughly equal weight."},
  {c:"Grammar",t:"All nouns have a gender (masculine or feminine). When in doubt, learn the article with the noun."},
  {c:"Grammar",t:"Adjectives in French agree with the noun they describe in gender and number."},
  {c:"Grammar",t:"'Du', 'de la', and 'des' are partitive articles meaning 'some' — used with uncountable nouns."},
  {c:"Grammar",t:"The verb 'être' (to be) is used for permanent states; 'avoir' (to have) is used for age, hunger, and many emotions."},
  {c:"Grammar",t:"Reflexive verbs use a reflexive pronoun: 'je me lève' = I get myself up."},
  {c:"Grammar",t:"The subjunctive is used after expressions of doubt, wish, or emotion: 'je veux que tu viennes'."},
  {c:"Grammar",t:"In questions, you can invert the subject and verb: 'Parlez-vous français?' instead of 'Vous parlez français?'"},
  {c:"Grammar",t:"Imparfait is used for ongoing past states and habits; passé composé for completed actions."},
  {c:"Grammar",t:"'Ne...pas' surrounds the conjugated verb to make it negative: 'Je ne sais pas.'"},
  {c:"Grammar",t:"Object pronouns go before the verb: 'Je le vois' (I see him/it), not 'Je vois le'."},
  {c:"Grammar",t:"The conditional mood uses the infinitive stem + imparfait endings: je parlerais, tu parlerais..."},
  {c:"Grammar",t:"'Dont' replaces 'de + relative pronoun': 'le livre dont je parle' = the book I'm talking about."},
  {c:"Grammar",t:"French has two future tenses: futur proche (going to) and futur simple (will)."},
  {c:"Grammar",t:"Possessive adjectives agree with the object, not the owner: 'son livre' can mean his or her book."},
  {c:"Grammar",t:"'Y' replaces a location or 'à + noun': 'J'y vais' = I'm going there."},
  {c:"Grammar",t:"'En' replaces 'de + noun': 'J'en veux' = I want some (of it)."},
  {c:"Grammar",t:"The plus-que-parfait (had done) uses the imparfait of avoir/être + past participle."},
  {c:"Grammar",t:"Adjectives of color that come from nouns are invariable: une robe orange, des robes orange."},
  {c:"Grammar",t:"'Quel', 'quelle', 'quels', 'quelles' all mean 'what/which' and agree with the noun."},
  {c:"Grammar",t:"The gérondif (en + present participle) expresses simultaneous actions: 'en mangeant' = while eating."},
  {c:"Vocabulary",t:"Learn words in context, not in isolation. A sentence sticks better than a flashcard."},
  {c:"Vocabulary",t:"Many English words ending in -tion are identical or near-identical in French: nation, action, passion."},
  {c:"Vocabulary",t:"English words ending in -ty often become -té in French: liberté, beauté, qualité."},
  {c:"Vocabulary",t:"English words ending in -ous often become -eux/-euse in French: dangereux, sérieux."},
  {c:"Vocabulary",t:"English words ending in -ary/-ory often become -aire/-oire in French: ordinaire, laboratoire."},
  {c:"Vocabulary",t:"The word 'fois' means 'time' as in an occurrence. 'Temps' means time as a concept or weather."},
  {c:"Vocabulary",t:"'Savoir' means knowing a fact; 'connaître' means knowing a person or place."},
  {c:"Vocabulary",t:"'Partir', 'quitter', and 'laisser' all relate to leaving but are not interchangeable."},
  {c:"Vocabulary",t:"'Entendre' means to hear; 'écouter' means to listen actively."},
  {c:"Vocabulary",t:"'Regarder' means to watch/look at; 'voir' means to see passively."},
  {c:"Vocabulary",t:"'Demander' means to ask, not to demand. 'Exiger' is closer to demand."},
  {c:"Vocabulary",t:"'Actuellement' means currently, not actually. 'En fait' or 'vraiment' means actually."},
  {c:"Vocabulary",t:"'Sensible' means sensitive in French, not sensible. 'Raisonnable' means sensible."},
  {c:"Vocabulary",t:"'Formidable' means wonderful/fantastic, not intimidating."},
  {c:"Vocabulary",t:"'Sympathique' (sympa) means nice/friendly, not sympathetic. 'Compatissant' means sympathetic."},
  {c:"Vocabulary",t:"Learn antonym pairs together: grand/petit, rapide/lent, chaud/froid."},
  {c:"Vocabulary",t:"Body parts are useful for idioms: 'avoir le cafard' (to be depressed) literally means to have the cockroach."},
  {c:"Vocabulary",t:"Food vocabulary is a great way to learn gender patterns and everyday conversation."},
  {c:"Vocabulary",t:"Weather expressions use 'il fait': il fait chaud, il fait froid, il fait beau."},
  {c:"Vocabulary",t:"Days of the week and months are not capitalized in French."},
  {c:"Speaking",t:"Don't wait until you're 'ready' to speak. Imperfection is part of the process."},
  {c:"Speaking",t:"Narrate your daily routine in French mentally as you go through it."},
  {c:"Speaking",t:"Record yourself speaking and listen back. You'll catch errors you didn't hear in the moment."},
  {c:"Speaking",t:"Filler words like 'euh', 'ben', 'bah', and 'donc' make you sound more natural."},
  {c:"Speaking",t:"'Quoi' added to the end of a sentence is a very colloquial filler: 'C'est comme ça, quoi.'"},
  {c:"Speaking",t:"French speakers often drop 'ne' in casual speech: 'Je sais pas' instead of 'Je ne sais pas'."},
  {c:"Speaking",t:"Try shadowing: listen to a native speaker and repeat immediately after them."},
  {c:"Speaking",t:"Think in French, even if just for a few minutes a day. Translate your thoughts."},
  {c:"Speaking",t:"Don't translate from English — aim to think directly in French as you advance."},
  {c:"Speaking",t:"Practice common question patterns until they're automatic: Où est...? Qu'est-ce que...? Comment...?"},
  {c:"Listening",t:"French radio (like France Inter) is great for immersion at natural speed."},
  {c:"Listening",t:"Start with content made for learners, then gradually move to native-speed material."},
  {c:"Listening",t:"Watch French films with French subtitles — not English ones."},
  {c:"Listening",t:"Podcasts like 'Coffee Break French' or 'Français Authentique' are excellent for commutes."},
  {c:"Listening",t:"Don't try to understand every word. Focus on grasping the main idea first."},
  {c:"Listening",t:"Re-listen to the same audio multiple times — you'll catch more each time."},
  {c:"Listening",t:"Pay attention to rhythm and intonation, not just words. Melody carries meaning."},
  {c:"Listening",t:"YouTube channels in French on topics you already love make listening less like studying."},
  {c:"Listening",t:"Try transcribing short clips — it forces you to hear every word carefully."},
  {c:"Listening",t:"Accents vary greatly: Parisian, Québécois, African French. Expose yourself to all of them."},
  {c:"Reading",t:"Start with graded readers designed for your level before tackling novels."},
  {c:"Reading",t:"Read children's books in French — simple vocabulary, full sentences, cultural context."},
  {c:"Reading",t:"French news sites like Le Monde or 20 Minutes give you authentic written French daily."},
  {c:"Reading",t:"When you encounter an unknown word, try to guess from context before reaching for a dictionary."},
  {c:"Reading",t:"Read aloud to combine reading practice with pronunciation training."},
  {c:"Reading",t:"Comics (BDs) like Astérix use colloquial language and are full of cultural references."},
  {c:"Reading",t:"Don't stop reading every time you hit an unknown word. Read for flow first."},
  {c:"Reading",t:"Read the same text multiple times. Familiarity reveals grammar patterns you missed the first time."},
  {c:"Reading",t:"Annotate as you read: mark unknown words, interesting expressions, grammar you notice."},
  {c:"Reading",t:"Try reading parallel texts — same content in English and French side by side."},
  {c:"Writing",t:"Keep a daily journal in French. Even three sentences a day builds a habit."},
  {c:"Writing",t:"Write about topics you know well in English — the challenge is expression, not ideas."},
  {c:"Writing",t:"Use 'donc', 'alors', 'cependant', and 'pourtant' to connect ideas elegantly."},
  {c:"Writing",t:"Avoid translating English sentence structures. French often prefers shorter, cleaner sentences."},
  {c:"Writing",t:"Vary your vocabulary. Don't use 'dire' every time — try 'affirmer', 'ajouter', 'préciser'."},
  {c:"Writing",t:"Proofread for gender agreement first, then verb conjugation, then accents."},
  {c:"Writing",t:"Accents change meaning: ou (or) vs où (where), a (has) vs à (at/to)."},
  {c:"Writing",t:"The cedilla (ç) softens the C before a, o, u: garçon, français."},
  {c:"Writing",t:"Practice writing emails in French — a real-world format that forces polite, structured language."},
  {c:"Writing",t:"Get your writing corrected on platforms like italki or HelloTalk."},
  {c:"Culture",t:"Understanding French culture deepens your grasp of the language — they're inseparable."},
  {c:"Culture",t:"'Tu' vs 'vous': use 'vous' with strangers, elders, and in formal settings. 'Tu' with friends and peers."},
  {c:"Culture",t:"The French take meal times seriously. Learning food vocabulary and dining etiquette opens conversations."},
  {c:"Culture",t:"Verlan is French back-slang: 'l'envers' becomes 'verlan', 'fou' becomes 'ouf'. Common in youth speech."},
  {c:"Culture",t:"French people often greet with 'la bise' (cheek kisses). The number varies by region."},
  {c:"Culture",t:"'On' informally replaces 'nous' in spoken French: 'On y va' = Let's go."},
  {c:"Culture",t:"French has formal written registers that differ significantly from spoken everyday French."},
  {c:"Culture",t:"Learning a few phrases in regional languages (Breton, Alsatian) shows cultural awareness."},
  {c:"Culture",t:"French cinema is rich and widely accessible — a great cultural and linguistic resource."},
  {c:"Culture",t:"Francophone Africa, Québec, Belgium, and Switzerland all have distinct French flavors worth exploring."},
  {c:"Motivation",t:"Fluency is not a destination — it's a continuous practice. Enjoy the journey."},
  {c:"Motivation",t:"Every mistake is evidence that you tried. Errors are how the brain recalibrates."},
  {c:"Motivation",t:"Connect your learning to something you love: French music, sport, food, travel, cinema."},
  {c:"Motivation",t:"Set micro goals: learn 5 new words today, write one paragraph, watch 10 minutes of French TV."},
  {c:"Motivation",t:"Track your progress. Looking back at where you started is one of the best motivators."},
  {c:"Motivation",t:"Find a language partner. Accountability and real conversation accelerate progress fast."},
  {c:"Motivation",t:"Rest is part of learning. Sleep consolidates vocabulary and grammar you studied that day."},
  {c:"Motivation",t:"Comparing yourself to native speakers is unfair. Compare yourself to who you were last month."},
  {c:"Motivation",t:"Celebrate small wins: your first successful phone call, your first joke in French."},
  {c:"Motivation",t:"Consistency beats intensity. 15 minutes every day beats 2 hours once a week."},
  {c:"Idioms",t:"'Avoir le cafard' = to feel down/depressed. Literally: to have the cockroach."},
  {c:"Idioms",t:"'Casser les pieds' = to annoy someone. Literally: to break someone's feet."},
  {c:"Idioms",t:"'Il pleut des cordes' = it's raining heavily. Literally: it's raining ropes."},
  {c:"Idioms",t:"'Avoir d'autres chats à fouetter' = to have bigger fish to fry. Literally: to have other cats to whip."},
  {c:"Idioms",t:"'Poser un lapin' = to stand someone up. Literally: to place a rabbit."},
  {c:"Idioms",t:"'Avoir le coup de foudre' = to fall in love at first sight. Literally: to receive a lightning bolt."},
  {c:"Idioms",t:"'Tomber dans les pommes' = to faint. Literally: to fall into the apples."},
  {c:"Idioms",t:"'Coûter les yeux de la tête' = to cost a fortune. Literally: to cost the eyes of the head."},
  {c:"Idioms",t:"'Faire la grasse matinée' = to sleep in. Literally: to do the fat morning."},
  {c:"Idioms",t:"'Avoir le beurre et l'argent du beurre' = to want it both ways. Literally: to have the butter and the butter money."},
  {c:"Idioms",t:"'Revenons à nos moutons' = let's get back on topic. Literally: let's return to our sheep."},
  {c:"Idioms",t:"'C'est la croix et la bannière' = it's a real hassle. Literally: it's the cross and the banner."},
  {c:"Idioms",t:"'Avoir le vent en poupe' = to be on a roll. Literally: to have the wind at the stern."},
  {c:"Idioms",t:"'Prendre ses jambes à son cou' = to run away fast. Literally: to take your legs to your neck."},
  {c:"Idioms",t:"'Mettre son grain de sel' = to give unsolicited opinions. Literally: to add your grain of salt."},
  {c:"Grammar",t:"'Ce qui' is the subject of a relative clause; 'ce que' is the object: 'Ce qui m'intéresse, c'est ce que tu fais.'"},
  {c:"Grammar",t:"The passive voice uses être + past participle: 'Le gâteau a été mangé par Pierre.'"},
  {c:"Grammar",t:"Negation with infinitives puts both parts before the verb: 'ne pas vouloir', not 'vouloir pas'."},
  {c:"Grammar",t:"After most prepositions, use the infinitive not the subjunctive: 'pour faire', 'avant de partir'."},
  {c:"Grammar",t:"'Depuis' + present tense expresses an action that started in the past and is still ongoing."},
  {c:"Grammar",t:"'Venir de' + infinitive expresses the recent past: 'Je viens de manger' = I just ate."},
  {c:"Grammar",t:"Indirect speech shifts tenses back: 'Il dit qu'il viendra' → 'Il a dit qu'il viendrait'."},
  {c:"Grammar",t:"'Même' changes meaning by position: 'le même homme' vs 'l'homme même'."},
  {c:"Grammar",t:"'Tout' can be adjective, pronoun, or adverb — its agreement rules differ in each case."},
  {c:"Grammar",t:"The impersonal 'il' is used for weather, time, and set expressions: 'Il faut', 'Il s'agit de'."},
  {c:"Vocabulary",t:"Learn verbs in families: porter, apporter, emporter, supporter, reporter all share a root."},
  {c:"Vocabulary",t:"'Avoir l'air' means to seem/look: 'Elle a l'air fatiguée' = She looks tired."},
  {c:"Vocabulary",t:"Time adverbs: hier (yesterday), aujourd'hui (today), demain (tomorrow), maintenant (now)."},
  {c:"Vocabulary",t:"Learn the most common 500 French words first — they cover the vast majority of everyday speech."},
  {c:"Vocabulary",t:"Numbers up to 100 should be automatic. Practice counting backwards to reinforce them."},
  {c:"Vocabulary",t:"'En train de' + infinitive describes an action in progress: 'Je suis en train de manger' = I am eating."},
  {c:"Vocabulary",t:"Adverbs are often formed by adding -ment to the feminine adjective: rapide → rapidement."},
  {c:"Vocabulary",t:"'Plaire' means to please/be pleasing to: 'Ce film me plaît' = I like this film."},
  {c:"Vocabulary",t:"'Manquer' works opposite to English: 'Tu me manques' = I miss you (you are lacking to me)."},
  {c:"Vocabulary",t:"Colors in French: rouge, bleu, vert, jaune, noir, blanc, gris, rose, violet, orange, marron."},
  {c:"Speaking",t:"Linking words make your speech flow: 'donc', 'alors', 'pourtant', 'par contre', 'en fait'."},
  {c:"Speaking",t:"Practice set phrases for buying time: 'C'est une bonne question...', 'Voyons voir...', 'Comment dire...'"},
  {c:"Speaking",t:"Mimic the rhythm of French — it flows in sense-groups, not word by word."},
  {c:"Speaking",t:"Sing along to French songs. Lyrics are packed with natural vocabulary and rhythm."},
  {c:"Speaking",t:"Even if your grammar is imperfect, clear communication beats grammatical silence every time."},
  {c:"Speaking",t:"'Pardon?' and 'Vous pouvez répéter?' are your best friends early on."},
  {c:"Speaking",t:"Greetings and pleasantries should be effortless — drill them until they're instinctive."},
  {c:"Speaking",t:"Express opinions with: 'À mon avis', 'Je pense que', 'Il me semble que', 'Selon moi'."},
  {c:"Speaking",t:"When you make a mistake, correct it out loud and move on. Don't dwell."},
  {c:"Speaking",t:"Imitate a French speaker you love — their rhythm, their speed, their intonation."},
  {c:"Pronunciation",t:"'Qu' is always pronounced like the English K — the U is silent: qui, que, quatre."},
  {c:"Pronunciation",t:"Double consonants are usually pronounced as one: commencer = co-mahn-say."},
  {c:"Pronunciation",t:"Elision: 'le' and 'la' drop the vowel before another vowel: l'ami, l'école."},
  {c:"Pronunciation",t:"'Gn' sounds like the Spanish ñ or the ny in canyon: montagne, ligne."},
  {c:"Pronunciation",t:"The French E caduc (mute e) can be dropped in fast speech: 'j'sais pas' for 'je ne sais pas'."},
  {c:"Pronunciation",t:"Intonation rises at the end of yes/no questions in conversational French."},
  {c:"Pronunciation",t:"'Oi' sounds like 'wa': moi, toi, boire, voilà."},
  {c:"Pronunciation",t:"Pay attention to syllabification — French divides syllables differently from English."},
  {c:"Pronunciation",t:"The sound 'an'/'en' are the same nasal vowel — practice with: enfant, ensemble, manger."},
  {c:"Pronunciation",t:"'In'/'ain'/'ein' are also the same nasal vowel: fin, pain, plein."},
  {c:"Culture",t:"French people say 'Bon courage' (good courage) to wish you strength — not 'bonne chance'."},
  {c:"Culture",t:"Café culture is central to French life. Learn the vocabulary for ordering and small talk."},
  {c:"Culture",t:"'C'est normal' is used frequently to mean 'it's fine/natural/expected' — not just 'normal'."},
  {c:"Culture",t:"The French education system uses a 20-point grading scale. 12/20 is actually decent."},
  {c:"Culture",t:"'La rentrée' in September is a major cultural moment — back to school, work, and routine."},
  {c:"Culture",t:"'Débrouillard' means resourceful and self-reliant — a highly admired trait in French culture."},
  {c:"Culture",t:"French has a strong literary tradition. Knowing a few key authors impresses native speakers."},
  {c:"Culture",t:"'Convivialité' is a core French value — the art of eating and living well together."},
  {c:"Culture",t:"French administrative language is notoriously complex — even native speakers find it challenging."},
  {c:"Culture",t:"'Être bien dans sa peau' (to be comfortable in your skin) captures an important French value."},
  {c:"Motivation",t:"Learning French opens doors to 29 countries and 300 million speakers worldwide."},
  {c:"Motivation",t:"French is the language of diplomacy, fashion, gastronomy, and international institutions."},
  {c:"Motivation",t:"You already know hundreds of French words through English — cognates are your head start."},
  {c:"Motivation",t:"Every French word you learn rewires your brain slightly. Language learning is brain training."},
  {c:"Motivation",t:"Even a plateau is progress — your brain is consolidating while you feel stuck."},
  {c:"Motivation",t:"Set a meaningful goal: a trip to Paris, a French film without subtitles, a DELF certification."},
  {c:"Motivation",t:"Your accent is not an obstacle. Many French speakers find foreign accents charming."},
  {c:"Motivation",t:"The B2 level is a turning point — conversations start to feel natural and enjoyable."},
  {c:"Motivation",t:"One good conversation with a native speaker can do more than a week of textbooks."},
  {c:"Motivation",t:"Language is a superpower. You are literally building a new mind with every lesson."},
];

let idx = Math.floor((Date.now() / 86400000)) % TIPS.length;

function render(){
  const t = TIPS[idx];
  document.getElementById('cat').textContent = t.c;
  document.getElementById('conseil-text').textContent = t.t;
  document.getElementById('day').textContent = `Tip ${idx+1} of ${TIPS.length}`;
}
function next(){idx=(idx+1)%TIPS.length;render();}
function prev(){idx=(idx-1+TIPS.length)%TIPS.length;render();}
function goToday(){idx=Math.floor((Date.now()/86400000))%TIPS.length;render();}
document.addEventListener('DOMContentLoaded', render);